[package]
edition = "2021"
name = "glsl-types"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
glsl = "7.0.0"
wasm-bindgen = "0.2.92"
