// DO NOT EDIT THIS FILE
// This file is generated by glsl-types

const SHADER_SOURCE = ``;


export type P1Uniforms = {
};

export type P1 = {
    uniforms: P1Uniforms;
    shaderSource: typeof SHADER_SOURCE;
};
