// DO NOT EDIT THIS FILE
// This file is generated by glsl-types

const SHADER_SOURCE = ``;


export type Program1Uniforms = {
};

export type Program1 = {
    uniforms: Program1Uniforms;
    shaderSource: typeof SHADER_SOURCE;
};
