// DO NOT EDIT THIS FILE
// This file is generated by glsl-types

type iResolution = f32;
type iTime = f32;
type _PSNoiseOffset = [f32; 3];
type _PSNoiseGlobalScale = f32;
type _PSWaterHeight = f32;
type _PSWaterDepthOffset = f32;
type _PSMaxHeightOffset = f32;
type _PlanetColor1 = [f32; 3];
type _PlanetColor2 = [f32; 3];
type _PSNoiseScales = [f32; 2];
type _SecondaryNoiseStrengthGround = f32;
type _MaxScrewTerrain = f32;
type _PSDensityOffset = f32;
type _SurfaceMinLight = f32;
type _GridHalfSize = f32;
type _VoxelNormalInterp = f32;
type _EnableVoxelizer = bool;
type _PlanetSurfaceWaterStepSize = f32;
type _PlanetSurfaceWaterMaxStepCount = f32;
type _WaterColorDepth = [f32; 3];
type _WaterColor = [f32; 3];
type _WaterMaterialSmoothStep = [f32; 2];
type _WaterNormalScale = f32;
type _WaterSurfaceMinLight = f32;
type _WaterNormalStrength = f32;
type _SpecularParams = [f32; 2];
type _WaterMoveSpeed = f32;
type _CloudTransparency = f32;
type _CloudColor1 = [f32; 3];
type _CloudColor2 = [f32; 3];
type _MaxScrewCloud = f32;
type _BreakDistanceCloud = f32;
type _CloudMidDistance = f32;
type _CloudHalfHeight = f32;
type _CloudNoiseScales = [f32; 2];
type _CloudNoiseOffset = [f32; 3];
type _CloudNoiseGlobalScale = f32;
type _SecondaryNoiseStrength = f32;
type _CloudDensityMultiplier = f32;
type _CloudDensityOffset = f32;
type _CloudMoveSpeed = f32;
type _CloudsStepSize = f32;
type _CloudsMaxStepCount = f32;
type _CloudsPosterize = bool;
type _CloudsPosterizeCount = f32;
type _AmbientColor = [f32; 3];
type _AmbientPower = f32;
type _CylinderHeight = f32;
type _CylinderRad = f32;

struct ExampleUniforms {
    iResolution: iResolution,
    iTime: iTime,
    _PSNoiseOffset: _PSNoiseOffset,
    _PSNoiseGlobalScale: _PSNoiseGlobalScale,
    _PSWaterHeight: _PSWaterHeight,
    _PSWaterDepthOffset: _PSWaterDepthOffset,
    _PSMaxHeightOffset: _PSMaxHeightOffset,
    _PlanetColor1: _PlanetColor1,
    _PlanetColor2: _PlanetColor2,
    _PSNoiseScales: _PSNoiseScales,
    _SecondaryNoiseStrengthGround: _SecondaryNoiseStrengthGround,
    _MaxScrewTerrain: _MaxScrewTerrain,
    _PSDensityOffset: _PSDensityOffset,
    _SurfaceMinLight: _SurfaceMinLight,
    _GridHalfSize: _GridHalfSize,
    _VoxelNormalInterp: _VoxelNormalInterp,
    _EnableVoxelizer: _EnableVoxelizer,
    _PlanetSurfaceWaterStepSize: _PlanetSurfaceWaterStepSize,
    _PlanetSurfaceWaterMaxStepCount: _PlanetSurfaceWaterMaxStepCount,
    _WaterColorDepth: _WaterColorDepth,
    _WaterColor: _WaterColor,
    _WaterMaterialSmoothStep: _WaterMaterialSmoothStep,
    _WaterNormalScale: _WaterNormalScale,
    _WaterSurfaceMinLight: _WaterSurfaceMinLight,
    _WaterNormalStrength: _WaterNormalStrength,
    _SpecularParams: _SpecularParams,
    _WaterMoveSpeed: _WaterMoveSpeed,
    _CloudTransparency: _CloudTransparency,
    _CloudColor1: _CloudColor1,
    _CloudColor2: _CloudColor2,
    _MaxScrewCloud: _MaxScrewCloud,
    _BreakDistanceCloud: _BreakDistanceCloud,
    _CloudMidDistance: _CloudMidDistance,
    _CloudHalfHeight: _CloudHalfHeight,
    _CloudNoiseScales: _CloudNoiseScales,
    _CloudNoiseOffset: _CloudNoiseOffset,
    _CloudNoiseGlobalScale: _CloudNoiseGlobalScale,
    _SecondaryNoiseStrength: _SecondaryNoiseStrength,
    _CloudDensityMultiplier: _CloudDensityMultiplier,
    _CloudDensityOffset: _CloudDensityOffset,
    _CloudMoveSpeed: _CloudMoveSpeed,
    _CloudsStepSize: _CloudsStepSize,
    _CloudsMaxStepCount: _CloudsMaxStepCount,
    _CloudsPosterize: _CloudsPosterize,
    _CloudsPosterizeCount: _CloudsPosterizeCount,
    _AmbientColor: _AmbientColor,
    _AmbientPower: _AmbientPower,
    _CylinderHeight: _CylinderHeight,
    _CylinderRad: _CylinderRad,
}

pub struct Example {
    uniforms: ExampleUniforms,
}
